AssetInventory/Areas/QuanTriVien/Controllers/NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetInventory.Models;

namespace AssetInventory.Areas.QuanTriVien.Controllers
{
    public class NguoiDungController : Controller
    {
        AIDataContext db = new AIDataContext();

        // GET: QuanTriVien/NguoiDung
        public ActionResult Index()
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {
                return View();

            }
        }


        [HttpGet]
        public JsonResult Select_TongSoLuong_NguoiDung()
        {
            var get_data = from s in db.NguoiDungs.OrderByDescending(a => a.MaND)
                           join dv in db.DonVis on s.MaDV equals dv.MaDV
                           select new { s.MaDV, s.MaND, s.TenDangNhap, s.MatKhau, s.HoVaTen, s.ChucDanh, s.PhanQuyen, s.SoDienThoai, s.Email, s.DiaChi, s.NgayCapNhat, s.NgayTao, dv.TenDV };
            return Json(new {code = true, SoLuong = get_data.Count() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_NguoiDung()
        {
            var get_data = from s in db.NguoiDungs.OrderByDescending(a => a.MaND)
                           join dv in db.DonVis on s.MaDV equals dv.MaDV
                           select new { s.MaDV, s.MaND, s.TenDangNhap, s.MatKhau, s.HoVaTen, s.ChucDanh, s.PhanQuyen, s.SoDienThoai, s.Email, s.DiaChi, s.NgayCapNhat, s.NgayTao, dv.TenDV };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_NguoiDung_By_MaND(int MaND)
        {
            var get_data = from s in db.NguoiDungs.OrderByDescending(a => a.MaND)
                           where s.MaND == MaND
                           join dv in db.DonVis on s.MaDV equals dv.MaDV
                           select new { s.MaDV, s.MaND, s.TenDangNhap, s.MatKhau, s.HoVaTen, s.ChucDanh, s.PhanQuyen, s.SoDienThoai, s.Email, s.DiaChi, s.NgayCapNhat, s.NgayTao, dv.TenDV };
            return Json(new { code = true, data = get_data }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Insert_NguoiDung(NguoiDung nd)
        {
            var check_nguoidung = from s in db.NguoiDungs.OrderByDescending(a => a.MaND)
                                  where s.TenDangNhap == nd.TenDangNhap
                                  select s;
            if (check_nguoidung.Count() >= 1)
            {
                return Json(new { Message = "Thêm mới người dùng thất bại, tên tài khoản này đã tồn tại", code = false });
            }
            if (nd.PhanQuyen != 0 && nd.PhanQuyen != 1)
            {
                return Json(new { Message = "Thêm mới người dùng thất bại, phân quyền không hợp lệ", code = false });
            }
            nd.NgayTao = DateTime.Now;
            nd.NgayCapNhat = DateTime.Now;
            db.NguoiDungs.InsertOnSubmit(nd);
            db.SubmitChanges();
            NguoiDung kh_insert = (NguoiDung)Session["Admin"];
            NhatKyHoatDong nkhd = new NhatKyHoatDong();
            nkhd.TenDangNhap = kh_insert.TenDangNhap;
            nkhd.HoatDong = "Thêm";
            nkhd.ChiTietHoatDong = "Thêm người dùng";
            nkhd.NgayHoatDong = DateTime.Now;
            db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
            db.SubmitChanges();
            return Json(new { Message = "Thêm mới thành công", code = true });
        }

        [HttpPost]
        public JsonResult Update_NguoiDung(NguoiDung nd)
        {
            var check_nguoidung = from s in db.NguoiDungs.OrderByDescending(a => a.MaND)
                                  where s.TenDangNhap == nd.TenDangNhap
                                  select s;
            if (nd.PhanQuyen != 0 && nd.PhanQuyen != 1)
            {
                return Json(new { Message = "Sửa người dùng thất bại, phân quyền không hợp lệ", code = false });
            }
            try
            {
                var get_data = db.NguoiDungs.SingleOrDefault(c => c.MaND == nd.MaND);
                get_data.MaDV = nd.MaDV;
                get_data.TenDangNhap = nd.TenDangNhap;
                get_data.MatKhau = nd.MatKhau;
                get_data.HoVaTen = nd.HoVaTen;
                get_data.ChucDanh = nd.ChucDanh;
                get_data.PhanQuyen = nd.PhanQuyen;
                get_data.SoDienThoai = nd.SoDienThoai;
                get_data.Email = nd.Email;
                get_data.DiaChi = nd.DiaChi;
                get_data.NgayCapNhat = DateTime.Now;
                db.SubmitChanges();

                NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                NhatKyHoatDong nkhd = new NhatKyHoatDong();
                nkhd.TenDangNhap = kh_insert.TenDangNhap;
                nkhd.HoatDong = "Sửa";
                nkhd.ChiTietHoatDong = "Sửa người dùng có Mã Người Dùng là: " + nd.MaND;
                nkhd.NgayHoatDong = DateTime.Now;
                db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                db.SubmitChanges();
                return Json(new { code = true, msg = "Sửa thành công nha :3" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = false, msg = "Sửa hổng được, hình như có lỗi á :3" + ex.Message }, JsonRequestBehavior.AllowGet);
            }





        }

        [HttpPost]
        public JsonResult Delete_NguoiDung(NguoiDung nd)
        {
            try
            {
                var get_data = db.NguoiDungs.SingleOrDefault(c => c.MaND == nd.MaND);
                db.NguoiDungs.DeleteOnSubmit(get_data);
                db.SubmitChanges();

                NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                NhatKyHoatDong nkhd = new NhatKyHoatDong();
                nkhd.TenDangNhap = kh_insert.TenDangNhap;
                nkhd.HoatDong = "Xóa";
                nkhd.ChiTietHoatDong = "Xóa người dùng có Mã Người Dùng là: " + nd.MaND;
                nkhd.NgayHoatDong = DateTime.Now;
                db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                db.SubmitChanges();
                return Json(new { code = true, msg = "Xóa thành công nha :3" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = false, msg = "Xóa hổng được, hình như có lỗi á :3 \n Chi tiết lỗi: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

AssetInventory/Areas/QuanTriVien/Controllers/NhatKyHoatDongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetInventory.Models;

namespace AssetInventory.Areas.QuanTriVien.Controllers
{
    public class NhatKyHoatDongController : Controller
    {
        AIDataContext db = new AIDataContext();

        // GET: QuanTriVien/NhatKyHoatDong
        public ActionResult Index()
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {
                return View();

            }
        }


        [HttpGet]
        public JsonResult Select_NKHD()
        {
            var get_data = from s in db.NhatKyHoatDongs.OrderByDescending(a => a.NgayHoatDong)
                           select new { s.MaNKHD, s.TenDangNhap, s.HoatDong, s.ChiTietHoatDong, s.GhiChu, s.NgayHoatDong};
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }
    }
}

AssetInventory/Areas/QuanTriVien/Controllers/PhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetInventory.Models;
namespace AssetInventory.Areas.QuanTriVien.Controllers
{
    public class PhongController : Controller
    {
        AIDataContext db = new AIDataContext();


        // GET: QuanTriVien/Phong
        public ActionResult Index()
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {
                return View();

            }
        }


        [HttpGet]
        public JsonResult Select_TongSoLuong_Phong()
        {
            var get_data = from s in db.Phongs.OrderByDescending(a => a.MaKV)
                           join kvp in db.KhuVucPhongs on s.MaKV equals kvp.MaKV
                           join lp in db.LoaiPhongs on s.MaLP equals lp.MaLP
                           select new { s.MaPhong, s.MaKV, s.MaLP, s.TenPhong, kvp.TenKV, lp.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { code = true, SoLuong = get_data.Count() }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_Phong()
        {
            var get_data = from s in db.Phongs.OrderByDescending(a => a.MaKV)
                           join kvp in db.KhuVucPhongs on s.MaKV equals kvp.MaKV
                           join lp in db.LoaiPhongs on s.MaLP equals lp.MaLP
                           select new { s.MaPhong, s.MaKV, s.MaLP, s.TenPhong, kvp.TenKV, lp.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult Select_KhuVucPhong()
        {
            var get_data = from s in db.KhuVucPhongs.OrderByDescending(a => a.MaKV)
                           select new { s.MaKV, s.TenKV, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult Select_LoaiPhong()
        {
            var get_data = from s in db.LoaiPhongs.OrderByDescending(a => a.MaLP)
                           select new { s.MaLP, s.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }




        [HttpGet]
        public JsonResult Select_Phong_By_MaPhong(int MaPhong)
        {
            var get_data = from s in db.Phongs.OrderByDescending(a => a.MaKV)
                           where s.MaPhong == MaPhong
                           join kvp in db.KhuVucPhongs on s.MaKV equals kvp.MaKV
                           join lp in db.LoaiPhongs on s.MaLP equals lp.MaLP
                           select new { s.MaPhong, s.MaKV, s.MaLP, s.TenPhong, kvp.TenKV, lp.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { code = true, data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_KhuVucPhong_By_MaKV(int MaKV)
        {
            var get_data = from s in db.KhuVucPhongs.OrderByDescending(a => a.MaKV)
                           where s.MaKV == MaKV
                           select new { s.MaKV, s.TenKV, s.GhiChu, s.NgayCapNhat };
            return Json(new { code = true, data = get_data }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult Select_LoaiPhong_By_MaLP(int MaLP)
        {
            var get_data = from s in db.LoaiPhongs.OrderByDescending(a => a.MaLP)
                           where s.MaLP == MaLP
                           select new { s.MaLP, s.TenLP, s.GhiChu, s.NgayCapNhat };
            return Json(new { code = true, data = get_data }, JsonRequestBehavior.AllowGet);
        }

 

   



        [HttpPost]
        public JsonResult Insert_Phong(Phong p)
        {
            var check_phong = from s in db.Phongs.OrderByDescending(a => a.MaPhong)
                                  where s.TenPhong == p.TenPhong
                                  select s;
            if (check_phong.Count() >= 1)
            {
                return Json(new { Message = "Thêm mới phòng thất bại, tên phòng này đã tồn tại", code = false });
            }
            if (string.IsNullOrEmpty(p.GhiChu))
            {
                p.GhiChu = "Không có";
            }
            p.NgayTao = DateTime.Now;
            p.NgayCapNhat = DateTime.Now;
            db.Phongs.InsertOnSubmit(p);
            db.SubmitChanges();

            NguoiDung kh_insert = (NguoiDung)Session["Admin"];
            NhatKyHoatDong nkhd = new NhatKyHoatDong();
            nkhd.TenDangNhap = kh_insert.TenDangNhap;
            nkhd.HoatDong = "Thêm";
            nkhd.ChiTietHoatDong = "Thêm mới phòng";
            nkhd.NgayHoatDong = DateTime.Now;
            db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
            db.SubmitChanges();
            return Json(new { Message = "Thêm mới thành công", code = true });
        }

        [HttpPost]
        public JsonResult Insert_KhuVucPhong(KhuVucPhong kvp)
        {
            var check_kvphong = from s in db.KhuVucPhongs.OrderByDescending(a => a.MaKV)
                              where s.TenKV == kvp.TenKV
                              select s;
            if (check_kvphong.Count() >= 1)
            {
                return Json(new { Message = "Thêm mới kv phòng thất bại, tên kv phòng này đã tồn tại", code = false });
            }
            if (string.IsNullOrEmpty(kvp.GhiChu))
            {
                kvp.GhiChu = "Không có";
            }
            kvp.NgayTao = DateTime.Now;
            kvp.NgayCapNhat = DateTime.Now;
            db.KhuVucPhongs.InsertOnSubmit(kvp);
            db.SubmitChanges();

            NguoiDung kh_insert = (NguoiDung)Session["Admin"];
            NhatKyHoatDong nkhd = new NhatKyHoatDong();
            nkhd.TenDangNhap = kh_insert.TenDangNhap;
            nkhd.HoatDong = "Thêm";
            nkhd.ChiTietHoatDong = "Thêm mới khu vực phòng";
            nkhd.NgayHoatDong = DateTime.Now;
            db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
            db.SubmitChanges();
            return Json(new { Message = "Thêm mới thành công", code = true });
        }

        [HttpPost]
        public JsonResult Insert_LoaiPhong(LoaiPhong lp)
        {
            var check_loaiphong = from s in db.LoaiPhongs.OrderByDescending(a => a.MaLP)
                                where s.TenLP == lp.TenLP
                                select s;
            if (check_loaiphong.Count() >= 1)
            {
                return Json(new { Message = "Thêm mới loại phòng thất bại, tên loại phòng này đã tồn tại", code = false });
            }
            if (string.IsNullOrEmpty(lp.GhiChu))
            {
                lp.GhiChu = "Không có";
            }
            lp.NgayTao = DateTime.Now;
            lp.NgayCapNhat = DateTime.Now;
            db.LoaiPhongs.InsertOnSubmit(lp);
            db.SubmitChanges();

            NguoiDung kh_insert = (NguoiDung)Session["Admin"];
            NhatKyHoatDong nkhd = new NhatKyHoatDong();
            nkhd.TenDangNhap = kh_insert.TenDangNhap;
            nkhd.HoatDong = "Thêm";
            nkhd.ChiTietHoatDong = "Thêm mới loại phòng";
            nkhd.NgayHoatDong = DateTime.Now;
            db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
            db.SubmitChanges();
            return Json(new { Message = "Thêm mới thành công", code = true });
        }



        [HttpPost]
        public JsonResult Update_Phong(Phong p)
        {
            try
            {
                var get_data = db.Phongs.SingleOrDefault(c => c.MaPhong == p.MaPhong);
                get_data.TenPhong = p.TenPhong;
                get_data.MaKV = p.MaKV;
                get_data.MaLP = p.MaLP;
                get_data.GhiChu = p.GhiChu;
                get_data.NgayCapNhat = DateTime.Now;
                db.SubmitChanges();

                NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                NhatKyHoatDong nkhd = new NhatKyHoatDong();
                nkhd.TenDangNhap = kh_insert.TenDangNhap;
                nkhd.HoatDong = "Sửa";
                nkhd.ChiTietHoatDong = "Sửa phòng có ID là: " + p.MaPhong;
                nkhd.NgayHoatDong = DateTime.Now;
                db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                db.SubmitChanges();
                return Json(new { code = true, msg = "Sửa thành công nha :3" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = false, msg = "Sửa hổng được, hình như có lỗi á :3" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Update_KhuVucPhong(KhuVucPhong kvp)
        {
            try
            {
                var get_data = db.KhuVucPhongs.SingleOrDefault(c => c.MaKV == kvp.MaKV);
                get_data.TenKV = kvp.TenKV;
                get_data.GhiChu = kvp.GhiChu;
                get_data.NgayCapNhat = DateTime.Now;
                db.SubmitChanges();

                NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                NhatKyHoatDong nkhd = new NhatKyHoatDong();
                nkhd.TenDangNhap = kh_insert.TenDangNhap;
                nkhd.HoatDong = "Sửa";
                nkhd.ChiTietHoatDong = "Sửa khu vực phòng có ID là: " + kvp.MaKV;
                nkhd.NgayHoatDong = DateTime.Now;
                db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                db.SubmitChanges();
                return Json(new { code = true, msg = "Sửa thành công nha :3" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = false, msg = "Sửa hổng được, hình như có lỗi á :3" + ex.Message }, JsonRequestBehavior.AllowGet);
            }





        }

        [HttpPost]

AssetInventory/Areas/QuanTriVien/Views/TrangChu/Index.cshtml
@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Areas/QuanTriVien/Views/Shared/_LayoutQuanTriVien.cshtml";

}


<div class="container-fluid">

    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="javascript: void(0);">Trang chủ</a></li>
                        <li class="breadcrumb-item active">Trang tổng quan</li>
                    </ol>
                </div>
                <h4 class="page-title">Trang tổng quan</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card widget-inline">
                <div class="card-body p-0">
                    <div class="row g-0">
                        <div class="col-sm-6 col-xl-4">
                            <div class="card shadow-none m-0">
                                <div class="card-body text-center">
                                    <i class="dripicons-archive text-muted" style="font-size: 24px;"></i>
                                    <h3><span id="TongSL_TaiSan">29</span></h3>
                                    <p class="text-muted font-15 mb-0">Tổng số lượng tài sản</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xl-4">
                            <div class="card shadow-none m-0 border-start">
                                <div class="card-body text-center">
                                    <i class="mdi mdi-google-classroom" style="font-size: 24px;"></i>
                                    <h3><span id="TongSL_PhongHoc">29</span></h3>
                                    <p class="text-muted font-15 mb-0">Tổng số phòng học</p>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6 col-xl-4">
                            <div class="card shadow-none m-0 border-start">
                                <div class="card-body text-center">
                                    <i class="dripicons-user-group text-muted" style="font-size: 24px;"></i>
                                    <h3><span id="TongSL_ThanhVien">31</span></h3>
                                    <p class="text-muted font-15 mb-0">Thành viên</p>
                                </div>
                            </div>
                        </div>



                    </div> <!-- end row -->
                </div>
            </div> <!-- end card-box-->
        </div> <!-- end col-->
    </div>
    <!-- end row-->


    <div class="row">

        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="dropdown float-end">
                        <a href="#" class="dropdown-toggle arrow-none card-drop" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="mdi mdi-dots-vertical"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Weekly Report</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Monthly Report</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Action</a>
                            <!-- item-->
                            <a href="javascript:void(0);" class="dropdown-item">Settings</a>
                        </div>
                    </div>
                    <h4 class="header-title mb-3">Các thao tác gần đây</h4>


                    <div class="table-responsive">
                        <table id ="NKHD" class="table table-centered table-nowrap table-hover mb-0">
                            <tbody>
                            
                                
                               
                                

                            </tbody>
                        </table>
                    </div> <!-- end table-responsive-->

                </div> <!-- end card body-->
            </div> <!-- end card -->
        </div><!-- end col-->
    </div>
    <!-- end row-->







</div>


<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("Select_TongSoLuong_NguoiDung", "NguoiDung")',
            dataType: 'json',
            contentType: 'application/json;charset=utf-8',
            success: function (data) {
                if (data.code == true) {
                    $("#TongSL_ThanhVien").text(data.SoLuong);
                } else {
                    $("#TongSL_ThanhVien").text(0);
                }
            }
        });

        $.ajax({
            type: 'GET',
            url: '@Url.Action("Select_TongSoLuong_Phong", "Phong")',
            dataType: 'json',
            contentType: 'application/json;charset=utf-8',
            success: function (data) {
                if (data.code == true) {
                    $("#TongSL_PhongHoc").text(data.SoLuong);
                } else {
                    $("#TongSL_PhongHoc").text(0);
                }
            }
        });


        $.ajax({
            type: 'GET',
            url: '@Url.Action("Select_TongSoLuong_TaiSan", "TaiSan")',
            dataType: 'json',
            contentType: 'application/json;charset=utf-8',
            success: function (data) {
                if (data.code == true) {
                    $("#TongSL_TaiSan").text(data.SoLuong);
                } else {
                    $("#TongSL_TaiSan").text(0);
                }
            }
        });
        LoadData_NKHD();
    })

function LoadData_NKHD() {
    var i = 0;
    $.ajax({
        type: 'GET',
        url: '@Url.Action("Select_NKHD", "NhatKyHoatDong")',
        dataType: 'json',
        contentType: 'application/json;charset=utf-8',
        success: function (data) {
            var items = '';
            $.each(data.data, function (i, item) {

                if (i <= 5) {
                    var rows = "<tr>"
                        + '<td><span class="text-muted font-13">Hoạt động</span> <br /><span class="badge badge-warning-lighten">' + item.HoatDong + '</span></td>'
                        + '<td><h5 class="font-14 my-1"><a href="javascript:void(0);" class="text-body">Chi tiết hoạt động</a></h5><span class="text-muted font-13">'+item.ChiTietHoatDong+'</span></td>'
                        + '<td><span class="text-muted font-13">Người thực hiện</span><h5 class="font-14 mt-1 fw-normal">'+item.TenDangNhap+'</h5></td>'
                        + '<td><span class="text-muted font-13">Thời gian thực hiện</span><h5 class="font-14 mt-1 fw-normal">' + ToJavaScriptDate(item.NgayHoatDong)+'</h5></td>'
                        + '<td class="table-action" style="width: 90px;"><a href="javascript: void(0);" class="action-icon"> <i class="mdi mdi-eye"></i></a></td>'
                        + "</tr>";
                    $('#NKHD').append(rows);
                }
                i++;

            });
        },
        error: function (ex) {
            alert("Error_Load_Data");
        }
    });
    return false;
}

</script>