AssetInventory/Areas/QuanTriVien/Controllers/BanKiemKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetInventory.Models;

namespace AssetInventory.Areas.QuanTriVien.Controllers
{
    public class BanKiemKeController : Controller
    {
        AIDataContext db = new AIDataContext();

        // GET: QuanTriVien/BanKiemKe
        public ActionResult Index()
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {
                return View();

            }
        }


        [HttpGet]
        public JsonResult Select_BanKiemKe(int MaPhieu)
        {
            var get_data = from s in db.BanKiemKes.OrderByDescending(a => a.MaPhieu)
                           where MaPhieu == s.MaPhieu
                           join p in db.DonVis on s.MaDV equals p.MaDV
                           select new 
                           { 
                               s.MaBanKiemKe,
                                s.MaPhieu,
                                p.TenDV,
                                s.HoVaTen,
                                s.ChucVu,
                           };
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public JsonResult Insert_BanKiemKe(BanKiemKe bkk)
        {
           
                try
                {

                    bkk.TrangThai = 0;
                    bkk.NgayTao = DateTime.Now;
                    bkk.NgayCapNhat = DateTime.Now;
                    if (string.IsNullOrEmpty(bkk.GhiChu))
                    {
                        bkk.GhiChu = "Không có";
                    }
                    db.BanKiemKes.InsertOnSubmit(bkk);
                    db.SubmitChanges();

                    NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                    NhatKyHoatDong nkhd = new NhatKyHoatDong();
                    nkhd.TenDangNhap = kh_insert.TenDangNhap;
                    nkhd.HoatDong = "Thêm";
                    nkhd.ChiTietHoatDong = "Thêm ban kiểm kê vào Mã Phiếu: " + bkk.MaPhieu;
                    nkhd.NgayHoatDong = DateTime.Now;
                    db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                    db.SubmitChanges();
                return Json(new { Message = "Thêm mới thành công", code = true });
                    

                }
                catch (Exception ex)
                {
                    return Json(new { Message = ex.Message, code = false });
                }
            

        }





        [HttpPost]
        public JsonResult Delete_BanKiemKe(int MaBanKiemKe)
        {
            try
            {
                var cd = db.BanKiemKes.SingleOrDefault(c => c.MaBanKiemKe == MaBanKiemKe);

                NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                NhatKyHoatDong nkhd = new NhatKyHoatDong();
                nkhd.TenDangNhap = kh_insert.TenDangNhap;
                nkhd.HoatDong = "Xóa";
                nkhd.ChiTietHoatDong = "Xóa ban kiểm kê ở Mã Phiếu: " + cd.MaPhieu;
                nkhd.NgayHoatDong = DateTime.Now;
                db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                db.SubmitChanges();


                db.BanKiemKes.DeleteOnSubmit(cd);
                db.SubmitChanges();

                
                return Json(new { code = 1, msg = "Xóa thành công nha :3" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 0, msg = "Xóa hổng được, hình như có lỗi á :3 \nChi tiết lỗi: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }



    }
}

AssetInventory/Areas/QuanTriVien/Controllers/KiemKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetInventory.Models;

namespace AssetInventory.Areas.QuanTriVien.Controllers
{
    public class KiemKeController : Controller
    {
        AIDataContext db = new AIDataContext();

        // GET: QuanTriVien/KiemKe
        public ActionResult Index()
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {
                return View();

            }
        }

        public ActionResult ChiTietPhieuKiemKe(int MaPhieu)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {

                var check_phieukiemke = from s in db.PhieuKiemKes
                                        where s.MaPhieu == MaPhieu
                                        select s;
                if (check_phieukiemke.Count() <= 0)
                {
                    return RedirectToAction("Index");
                }else
                {
                    var get = db.PhieuKiemKes.SingleOrDefault(c => c.MaPhieu == MaPhieu);
                    if (get.TrangThai == 0)
                    {
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }

                }
            }
        }

        public ActionResult Invoice(int MaPhieu)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {

                var check_phieukiemke = from s in db.PhieuKiemKes
                                        where s.MaPhieu == MaPhieu
                                        select s;
                if (check_phieukiemke.Count() <= 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    var get = db.PhieuKiemKes.SingleOrDefault(c => c.MaPhieu == MaPhieu);
                    if (get.TrangThai == 1)
                    {
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }

                }
            }
        }

        public ActionResult Invoice_2(int MaPhieu)
        {
            if (Session["Admin"] == null || Session["Admin"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "TrangChu");
            }
            else
            {

                var check_phieukiemke = from s in db.PhieuKiemKes
                                        where s.MaPhieu == MaPhieu
                                        select s;
                if (check_phieukiemke.Count() <= 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    var get = db.PhieuKiemKes.SingleOrDefault(c => c.MaPhieu == MaPhieu);
                    if (get.TrangThai == 1)
                    {
                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Index");
                    }

                }
            }
        }



        [HttpGet]
        public JsonResult Select_PhieuKiemKe()
        {
            var get_data = from s in db.PhieuKiemKes.OrderByDescending(a => a.MaPhieu)
                           join p in db.Phongs on s.MaPhong equals p.MaPhong
                           select new { s.MaPhieu, s.MaPhong, s.GhiChu, s.TrangThai, s.NgayCapNhat, s.NgayTao, p.TenPhong};
            return Json(new { data = get_data }, JsonRequestBehavior.AllowGet);
        }

      




        [HttpPost]
        public JsonResult Insert_PhieuKiemKe(PhieuKiemKe kk)
        {
            var check_phieukiemke = from s in db.PhieuKiemKes
                           where s.MaPhong == kk.MaPhong
                           select s;
            var check_phong = from s in db.Phongs
                           where s.MaPhong == kk.MaPhong
                           select s;
            var check_phanbo = from s in db.PhanBos
                              where s.MaPhong == kk.MaPhong
                              select s;
            if (check_phong.Count() <= 0)
            {
                return Json(new { Message = "Không có Phòng này!!!", code = -1 });
            }else if (check_phanbo.Count() <= 0)
            {
                return Json(new { Message = "Phòng này hiện chưa có tài sản, nên không thể kiểm kê!!!", code = -1 });
            }
            else if (check_phieukiemke.Count() <= 0) // nếu chưa có 
            {
                try
                {
                    // insert vào phân bố
                    kk.TrangThai = 0;
                    kk.NgayTao = DateTime.Now;
                    kk.NgayCapNhat = DateTime.Now;
                    if (string.IsNullOrEmpty(kk.GhiChu))
                    {
                        kk.GhiChu = "Không có";
                    }
                    db.PhieuKiemKes.InsertOnSubmit(kk);
                    db.SubmitChanges();
                    Insert_ChiTietPhieuKiem(kk.MaPhieu, kk.MaPhong);

                    NguoiDung kh_insert = (NguoiDung)Session["Admin"];
                    NhatKyHoatDong nkhd = new NhatKyHoatDong();
                    nkhd.TenDangNhap = kh_insert.TenDangNhap;
                    nkhd.HoatDong = "Thêm";
                    nkhd.ChiTietHoatDong = "Thêm mới phiếu kiểm kê";
                    nkhd.NgayHoatDong = DateTime.Now;
                    db.NhatKyHoatDongs.InsertOnSubmit(nkhd);
                    db.SubmitChanges();

                    return Json(new { Message = "Thêm mới thành công", code = 200 });
                }
                catch (Exception ex)
                {
                    return Json(new { Message = ex.Message, code = -1 });
                }
            }else
            {

                if (check_phieukiemke.FirstOrDefault().TrangThai == 0)
                {
                    return Json(new { Message = "Phòng này có phiếu kiểm kê chưa hoàn thành", code = -1 });
                }
                else
                {
                    // insert vào phiếu kiểm
                    kk.TrangThai = 0;
                    kk.NgayTao = DateTime.Now;
                    kk.NgayCapNhat = DateTime.Now;
                    if (string.IsNullOrEmpty(kk.GhiChu))
                    {
                        kk.GhiChu = "Không có";
                    }
                    db.PhieuKiemKes.InsertOnSubmit(kk);
                    db.SubmitChanges();
                    // insert vào phiếu kiểm


                    Insert_ChiTietPhieuKiem(kk.MaPhieu, kk.MaPhong);
                    return Json(new { Message = "Thêm mới thành công", code = 200 });
                }


            }
             
        }


        public bool Insert_ChiTietPhieuKiem(int MaPhieu, int MaPhong)
        {
            var select_PhanBo_By_MaPhong = from s in db.PhanBos
                                    where s.MaPhong == MaPhong
                                    join p in db.TaiSans on s.MaTS equals p.MaTS
                                    join p1 in db.NhomTaiSans on p.MaNhomTS equals p1.MaNhomTS 
                                    select new
                                    {
                                        p.MaNhomTS,
                                        p1.TenNhomTS,
                                        p.TenTS,
                                        p.GiaTri,
                                        s.SoLuong,
                                        p.HangSanXuat,
                                        p.NuocSanXuat,
                                        p.NamSanXuat,
                                    };
            var check_phieukiemke = from s in db.PhieuKiemKes
                                    where s.MaPhieu == MaPhieu
                                    select s;
            var check_chitiet_phieukiemke = from s in db.ChiTietPhieuKiemKes
                                    where s.MaPhieu == MaPhieu
                                    select s;
            if (check_phieukiemke.Count() >= 1)
            {
                if (check_phieukiemke.FirstOrDefault().TrangThai != 0)
                {
                    return true;
                }else if (check_phieukiemke.FirstOrDefault().TrangThai == 0 && check_chitiet_phieukiemke.Count() >= 1)
                {
                    return true;
                }
                else if (check_phieukiemke.FirstOrDefault().TrangThai == 0)
                {
                    for (int i = 0; i < select_PhanBo_By_MaPhong.Count(); i++)
                    {
                        ChiTietPhieuKiemKe inset_ctpkk = new ChiTietPhieuKiemKe();
                        inset_ctpkk.MaPhieu = MaPhieu;
                        inset_ctpkk.TenTS = select_PhanBo_By_MaPhong.Skip(i).FirstOrDefault().TenTS;
                        inset_ctpkk.TenNhomTS = select_PhanBo_By_MaPhong.Skip(i).FirstOrDefault().TenNhomTS;
                        inset_ctpkk.GiaTri = select_PhanBo_By_MaPhong.Skip(i).FirstOrDefault().GiaTri;
                        inset_ctpkk.SoLuong = select_PhanBo_By_MaPhong.Skip(i).FirstOrDefault().SoLuong;
                        inset_ctpkk.SoLuongThucTe = 0;
                        inset_ctpkk.ConTot = 0;
                        inset_ctpkk.KemPC = 0;
                        inset_ctpkk.MatPC = 0;

AssetInventory/Areas/QuanTriVien/Views/KiemKe/Index.cshtml
@{
    ViewBag.Title = "Kiểm kê tài sản";
    Layout = "~/Areas/QuanTriVien/Views/Shared/_LayoutQuanTriVien.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item active">
                        <a href="javascript: void(0);">Kiểm kê</a>
                    </li>
                    <li class="breadcrumb-item ">Kiểm kê tài sản</li>
                </ol>
            </div>
            <h4 class="page-title">Kiểm kê tài sản</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-4">
                        <a href="#" data-bs-toggle="modal" data-bs-target="#add_new_phieukiemke" class="btn btn-danger mb-2"><i class="mdi mdi-plus-circle me-2"></i> Tạo mới phiếu kiểm kê</a>
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-end">
                            <button type="button" class="btn btn-success mb-2 me-1"><i class="mdi mdi-cog"></i></button>
                            <button type="button" class="btn btn-light mb-2 me-1">Import</button>
                            <button type="button" class="btn btn-light mb-2">Export</button>
                        </div>
                    </div><!-- end col-->
                </div>
                <table id="table_phieukiemke" class="table table-bordered table-centered mb-0">
                    <thead>
                        <tr style="text-align:center">
                            <th style="width:100px">Mã phiếu</th>
                            <th>Tên phòng</th>
                            <th>Trạng thái</th>
                            <th>Ghi chú</th>
                            <th style="width:180px">Ngày cập nhất cuối cùng</th>
                            <th style="width:180px">Ngày tạo</th>
                            <th style="width:200px" class="text-center">Hành động</th>
                        </tr>
                    </thead>
                    <tbody style="text-align:center">
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>



<!-- modal add phieu kiem ke -->
<div id="add_new_phieukiemke" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="standard-modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="standard-modalLabel">Thêm mới phiếu kiểm kê</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"></button>
            </div>
            <div class="modal-body">

                <div class="mb-3">
                    <label for="example-select" class="form-label">Chọn phòng cần thêm phiếu kiểm kê: </label>
                    <select id ="MaPhong_PKK" name ="MaPhong_PKK" class="form-select" id="example-select">
                      
                    </select>
                </div>

                <div class="mb-3">
                    <label for="example-textarea" class="form-label">Ghi chú</label>
                    <textarea class="form-control" id="GhiChu_PKK" name="GhiChu_PKK" rows="5"></textarea>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light" data-bs-dismiss="modal">Đóng</button>
                <button type="button" id ="ThemMoi_PhieuKiemKe" class="btn btn-primary">Thêm mới</button>
            </div>
        </div>
    </div>
</div>



<script>


    $(document).ready(function () {

        var Table_PKK = $('#table_phieukiemke').DataTable({
            "ordering": false,
            responsive: true,
            paging: true,
        });

        var Table_CTPKK = $('#table_show_chitiet_phieukiem').DataTable({

            "ordering": false,
            responsive: true,
            paging: true,
        });


        Load_Data_DSPhong();
        LoadData_PKK(Table_PKK);




        $("#ThemMoi_PhieuKiemKe").click(function () {
            var MaPhong = $("#MaPhong_PKK").val();
            var GhiChu = $("#GhiChu_PKK").val();
            if (MaPhong == "") {
                ThongBao("Thông báo", "Bạn chưa chọn Phòng cần thêm phiếu kiểm kê");
            } else {
                $.confirm({ // xác nhận thêm
                    title: 'Thông báo',
                    content: "Bạn có chắc chắn muốn thêm phiếu kiểm kê",
                    theme: 'dark',
                    buttons: {
                        XacNhan: {

                            text: 'Xác nhận', btnClass: 'btn-success', action: function () {
                                var themmoi = ThemMoi_PhieuKiemKe(MaPhong, GhiChu);
                                if (themmoi == true) {
                                    setTimeout(function () {
                                        LoadData_PKK(Table_PKK);
                                        ThongBao("Thành công", "Thêm mới phiếu kiểm kê thành công");
                                    }, 100);
                                } else {
                                    ThongBao("Thất bại", "Thêm mới không thành công !!");
                                }
                            }
                        },
                        HuyBo: {
                            text: 'Hủy bỏ', btnClass: 'btn-warning', action: function () {
                                ThongBao("Thành công", "Đã hủy bỏ thêm phiếu kiểm kê !!!");
                            }
                        }
                    }
                });// end xác nhận thêm
            } // end if
        });



});






function Load_Data_DSPhong() {
    var Get_DSPhong = Get_Data_DSPhong();
    if (Get_DSPhong != "Error_Get_Data_DSPhong") {
        $("#MaPhong_PKK").empty();
        $('#MaPhong_PKK').append($('<option>', { value: "Chọn phòng....", text: "Chọn phòng...." }));
        $.each(Get_DSPhong.data, function (i, item) {
            $('#MaPhong_PKK').append($('<option>', { value: item.MaPhong, text: item.TenPhong }));
        });
    }
}

function LoadData_PKK(Name_DataTable) {
        var Show_TrangThai = "";
    Name_DataTable.clear().draw();
    $.ajax({
        type: 'GET',
        url: '@Url.Action("Select_PhieuKiemKe", "KiemKe")',
        dataType: 'json',
        contentType: 'application/json;charset=utf-8',
        async: false,
        cache: false,
        success: function (data) {
            var items = '';
            //<i class="mdi mdi-circle text-warning"></i> Shipped
            $.each(data.data, function (i, item) {
                if (item.TrangThai == 0) {
                    Show_TrangThai = '<i class="mdi mdi-circle text-warning"></i> Chưa hoàn thành';
                    Name_DataTable.row.add([
                        '<td><a class="text-body fw-bold">#' + item.MaPhieu + '</a></td>',
                        '<h4><span class="badge bg-primary text-light">' + item.TenPhong + '</span></h4>',
                        Show_TrangThai,
                        item.GhiChu,
                        ToJavaScriptDate(item.NgayCapNhat),
                        ToJavaScriptDate(item.NgayTao),
                        '<a href="KiemKe/ChiTietPhieuKiemKe?MaPhieu=' + item.MaPhieu + '" target="_blank" class="btn btn-dark">Chi tiết phiếu kiểm</a>'
                    ]).draw(false);
                } else {
                    Show_TrangThai = '<i class="mdi mdi-circle text-success"></i> Đã hoàn thành';
                    Name_DataTable.row.add([
                        '<td><a class="text-body fw-bold">#' + item.MaPhieu + '</a></td>',
                        '<h4><span class="badge bg-primary text-light">' + item.TenPhong + '</span></h4>',
                        Show_TrangThai,
                        item.GhiChu,
                        ToJavaScriptDate(item.NgayCapNhat),
                        ToJavaScriptDate(item.NgayTao),
                        '<a href="KiemKe/Invoice?MaPhieu=' + item.MaPhieu + '" target="_blank" class="btn btn-info"><i class="dripicons-print"></i> </a>'
                    ]).draw(false);
                }

                
            });
        },
        error: function (ex) {
            alert("Error_Load_Data");
        }
    });
    return false;
}





function Get_Data_DSPhong() {
    var result = "";
    $.ajax({
        type: 'GET',
        url: '@Url.Action("Select_Phong", "Phong")',
        dataType: 'json',
        contentType: 'application/json;charset=utf-8',
        async: false,
        cache: false,
        success: function(data) {
            result = data;
        },
        error: function(ex) {
            result = "Error_Get_Data_DSPhong";
        }
    });
    return result;
}



function ThemMoi_PhieuKiemKe(MaPhong, GhiChu) {
        var rt = false;
    $.ajax({
        url: '@Url.Action("Insert_PhieuKiemKe", "KiemKe")',
        dataType: "json",
        type: "POST",
        contentType: 'application/json; charset=utf-8',
        data: JSON.stringify({ MaPhong: MaPhong, GhiChu: GhiChu }),
        async: false,
        cache: false,
        success: function (data) {
            if (data.code == 200) {
                rt = true;
            } else {
                rt = false;
            }
        },
        error: function (xhr) {
            alert("Error_Load_Data");
        }
    })
    return rt;
}

    function ThongBao(title, content) {
        $.alert({
            title: title,
            theme: 'dark',
            content: content,
        });
    }
</script>

AssetInventory/Areas/QuanTriVien/Views/KiemKe/Invoice_2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Invoice</title>
    <link rel="icon" type="image/png" href="~/Content/Hinh/icon_tdmu.png">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>

<style>
    table, td, th {
        border: 1px solid;
    }

    table {
        width: 100%;
        border-collapse: collapse;
    }
</style>

<body>
    <div>
        <table id="invoice">

            <caption><center><h3>BIÊN BẢN KIỂM KÊ CÔNG CỤ DỤNG CỤ VÀ TÀI SẢN CỐ ĐỊNH</h3></center></caption>
            <caption id="BanKiemKe_Show" style="text-align:left">
                Ban kiểm kê gồm:		<br>



            </caption>


            <tr style="text-align:center">
                <td rowspan="2">Số TT</td>
                <td rowspan="2">Tên công cụ dụng cụ</td>
                <td rowspan="2">Mã số CCDC</td>
                <td rowspan="2">Năm sử dụng</td>
                <td colspan="2">Theo sổ kế toán</td>
                <td colspan="2">Theo sổ kiểm kê</td>
                <td colspan="3">Phẩm chất</td>
                <td rowspan="2">Ghi chú</td>
            </tr>
            <tr style="text-align:center">

                <td>Đơn vị tính</td>
                <td>Số lượng</td>
                <td>Đơn vị tính</td>
                <td>Số lượng</td>
                <td>Còn tốt</td>
                <td>Kém phẩm chất</td>
                <td>Mất phẩm chất</td>
            </tr>



        </table>
        <div id="BanKiemKe_Show_1" style="text-align: center; text-indent: 150px; float:left">
            <b><p>Ban kiểm kê</p></b>
        </div>



    </div>
</body>
</html>

























<script>
    $(document).ready(function () {
        const urlParams = new URLSearchParams(window.location.search);
        const MaPhieu = urlParams.get('MaPhieu');

        Show_ChiTietPhieuKiem(MaPhieu);
        Show_BanKiemKe(MaPhieu);

        window.print();

    })

function Show_ChiTietPhieuKiem(MaPhieu) {
    var stt = 1;
    var tong_sl = 0;
    var tong_sl_tt = 0;
    var tong_contot = 0;
    var tong_kempc = 0;
    var tong_matpc = 0;
    var Get_CTPhieuKiem = Get_Data_CTPhieuKiem(MaPhieu);
    if (Get_CTPhieuKiem != "Error_Get_Data_CTPhieuKiem") {
        $.each(Get_CTPhieuKiem.data, function (i, item) {
            tong_sl += item.SoLuong;
            tong_sl_tt += item.SoLuongThucTe;
            tong_contot += item.ConTot;
            tong_kempc += item.KemPC;
            tong_matpc += item.MatPC;
            $('#invoice').append(
                '<tr style="text-align:center">' +
                '<td>'+ stt++ +'</td>' +
                '<td>'+item.TenTS+'</td>' +
                '<td></td>' +
                '<td></td>' +
                '<td>Cái</td>' +
                '<td>' + item.SoLuong +'</td>' +
                '<td>Cái</td>' +
                '<td>' + item.SoLuongThucTe +'</td>' +
                '<td>' + item.ConTot +'</td>' +
                '<td>' + item.KemPC +'</td>' +
                '<td>' + item.MatPC +'</td>' +
                '<td>' + item.GhiChu +'</td>' +
                '</tr>'
            );
        });
        $('#invoice').append(
            '<tr style="text-align:center">' +
            '<td></td>' +
            '<td><b>Cộng</b></td>' +
            '<td></td>' +
            '<td></td>' +
            '<td></td>' +
            '<td><b>' + tong_sl + '</b></td>' +
            '<td></td>' +
            '<td><b>' + tong_sl_tt + '</b></td>' +
            '<td><b>' + tong_contot + '</b></td>' +
            '<td><b>' + tong_kempc + '</b></td>' +
            '<td><b>' + tong_kempc + '</b></td>' +
            '<td></td>' +
            '</tr>'
        );



    } else {

    }
}

function Show_BanKiemKe(MaPhieu) {
    var iii = 1;
    var Get_BanKK = Get_Data_BanKiemKe(MaPhieu);
    if (Get_BanKK != "Error_Get_Data_CTPhieuKiem") {
        $.each(Get_BanKK.data, function (i, item) {

            $('#BanKiemKe_Show').append(' - Ông ' + item.HoVaTen + '; Chức vụ: ' + item.ChucVu + '; Đại diện: ' + item.TenDV+'<br>');
            $('#BanKiemKe_Show_1').append('<b><p>' + item.HoVaTen + '</p></b>');


        });
        $('#BanKiemKe_Show').append('<b>Đã kiểm kê TSCĐ, kết quả như sau:</b>	<br>');


    } else {
    }
}
function Get_Data_CTPhieuKiem(MaPhieu) {
    var result = "";
    $.ajax({
        type: 'GET',
        url: '@Url.Action("Select_ChiTietPhieuKiemKe", "KiemKe")',
        dataType: 'json',
        data: { MaPhieu: MaPhieu },
        contentType: 'application/json;charset=utf-8',
        async: false,
        cache: false,
        success: function(data) {
            result = data;
        },
        error: function(ex) {
            result = "Error_Get_Data_CTPhieuKiem";
        }
    });
    return result;
}

function Get_Data_BanKiemKe(MaPhieu) {
    var result = "";
    $.ajax({
        type: 'GET',
        url: '@Url.Action("Select_BanKiemKe", "BanKiemKe")',
        dataType: 'json',
        data: { MaPhieu: MaPhieu },
        contentType: 'application/json;charset=utf-8',
        async: false,
        cache: false,
        success: function(data) {
            result = data;
        },
        error: function(ex) {
            result = "Error_Get_Data_BanKiemKe";
        }
    });
    return result;
}

</script>